# This setting will automatically accept all incoming public keys from minions.
auto_accept: true
user: root

# Defines sync schedule for master
# schedule:
#   sync_all_master:
#     function: saltutil.sync_all
#     seconds: 10
#     maxrunning: 1

# The loop_interval option controls the seconds for the master's Maintenance process check cycle.
# This process updates file server backends, cleans the job cache and executes the scheduler.
loop_interval: 10

worker_threads: 1
job_cache: False
