
log_level: info
log_datefmt: '%Y-%m-%dT%H:%M:%S'
log_fmt_console: '%(asctime)s.%(msecs)03dZ %(colorlevel)s%(colorname)s %(colormsg)s'

 # %(pathname)s
 # %(processName)s
# HOSTNAME 192.0.2.1 -  salt-master
# APP-NAME myproc - %(processName)s
# PROCID 8710 - %(process)d
# MSGID ID47 - %(funcName)s:L%(lineno)d
# STRUCTURED-DATA - -
# <165>1 2003-08-24T05:14:15.000003-07:00 192.0.2.1 myproc 8710 ID47 - %% It's time to make the do-nuts.
 # %(exc_info)s %(args)s
 # <13>1 2020-03-13T20:45:38.119Z dynamicwireless.name non 2426 ID931 [exampleSDID@32473 iut="3" eventSource="Application" eventID="1011"] Try to override the THX port, maybe it will reboot the neural interface!


log_datefmt_logfile: '%Y-%m-%dT%H:%M:%S'
log_fmt_logfile: '%(asctime)s.%(msecs)03dZ salt-master %(processName)s [attributes jid="%(jid)s" lineno="%(lineno)d" funcName="%(funcName)s" pathname="%(pathname)s" filename="%(filename)s" module="%(module)s" levelname="%(levelname)s" name="%(name)s"] %(message)s'
log_level_logfile: info
log_file: "udp://vector:9998"

# log_granular_levels:
#   'salt': 'warning'
#   'salt.modules': 'debug'
#   'salt.loader.saltmaster.ext.module.custom_module': 'all'
