file_roots:
  base:
    - /srv/roots/salt

# Defines how often to restart the master's FilesServerUpdate process.
fileserver_interval: 15
fileserver_backend:
  - roots

pillar_roots:
  base:
    - /srv/roots/pillar
