rest_cherrypy:
  port: 8000
  debug: True
  disable_ssl: True

external_auth:
  pam:
    salt_api:
      - .*
      - "@runner"
      - "@wheel"
      - "@jobs"

# https://docs.saltproject.io/en/master/ref/configuration/master.html#netapi-enable-clients
netapi_enable_clients:
  - local
  - local_async
  - local_batch
  - local_subset
  - runner
  - runner_async
  - ssh
  - wheel
  - wheel_async
