
log_level: info
log_datefmt: '%Y-%m-%dT%H:%M:%S'
log_fmt_console: '%(asctime)s.%(msecs)03dZ %(colorlevel)s%(colorname)s %(colormsg)s'

log_datefmt_logfile: '%Y-%m-%dT%H:%M:%S'
log_fmt_logfile: '%(asctime)s.%(msecs)03dZ salt-minion %(name)s [attributes jid="%(jid)s" lineno="%(lineno)d" funcName="%(funcName)s" pathname="%(pathname)s" filename="%(filename)s" module="%(module)s" levelname="%(levelname)s" name="%(name)s"] %(message)s'
log_level_logfile: info
log_file: "udp://vector:9998"
