[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root

[program:salt-master]
command=/bin/salt-master
stdout_logfile=/dev/fd/2
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:salt-api]
command=/bin/salt-api
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:salt-exporter]
command=/bin/salt-exporter --config-file /etc/salt/salt-exporter.yml
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true

